### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by pacificobob** [yui/yuicompressor#114]
I run into the following error when passing object values using dot notation:

```
[ERROR] missing name after . operator
```

This error occurs when I pass values to the function as follows:

```
myFunction(explanations.slide1.short, explanations.slide1.long);
```

It is possible to work around this error by passing arguments like this:

```
myFunction(explanations["slide1"]["short"], explanations["slide1"]["long"]);
```

I am not sure if it is the object references themselves that are causing the issue, or if it is due to the fact that they are being passed to functions; however, it would be nice to have both options available when referencing object values.

**Comment by solidcloudio** [comment]
getting this with jquery 3.1.1 also
