### ISSUE TITLE
Compression fails on IndexedDB .continue(); and .delete

### ISSUE THREAD

**Issue by kaspro** [yui/yuicompressor#122]
When using indexedDB's cursor, the .continue property doesn't seem to be recognized, throwing an error:
missing name after . operator

The code works fine otherwise:
 var cursor = event.target.result;
                    if (cursor){
                        myArray.push([cursor.key,cursor.value]);
                        cursor.continue(); // <--- Errors out here
.....
Taken example from here: https://developer.mozilla.org/en/docs/IndexedDB/Using_IndexedDB

The same thing happens with the .delete function - whereas the code works fine, but the error "missing name after . operator" ocurrs:
db.transaction(["myStore"], 'readwrite').objectStore("myStore").delete(args).onsuccess = function(event) {
                    callback(true);
                };

Using objectStore("myStore")['delete'](args) and cursor['continue']() solves the issue, as per http://stackoverflow.com/questions/7235436/why-they-use-reserved-keyword-continue-to-name-a-function-in-indexeddbs-curso

...BUT, the rendered output won't be accepted by eclipse

**Comment by tml** [comment]
Tracking all versions of this issue on #47, closing the rest so that I only have one bug to keep track of for all the variants of the problem.

**Comment by anibalsanchez** [comment]
The only workaround is to translate:

q.then().catch(); 

into:

q.then();
q['catch'](); 

It is ugly but it works.
