### ISSUE TITLE
Incorrect minified css style.

### ISSUE THREAD

**Issue by RWander** [yui/yuicompressor#162]
Before minification:
@keyframes target-fade {
  0% { text-shadow: 0 0 10px yellow; }
  100% { text-shadow: none; }
}
After minification:
@keyframes target-fade{0{text-shadow:0 0 10px yellow}100%{text-shadow:none}}

The '%' symbol is lost after 0. The minified style doesn't work.

The expected result is
@keyframes target-fade{0%{text-shadow:0 0 10px yellow}100%{text-shadow:none}}

this is the critical bug for me.

**Comment by Requilence** [comment]
@tml not fixed anyway in HEAD

**Comment by jochenberger** [comment]
Should be fixed in master (see #231)
