### ISSUE TITLE
FileNotFoundException on Windows

### ISSUE THREAD

**Issue by leperse** [yui/yuicompressor#167]
Had to use the the 2.4.7 version instead.

java: "C:/Program Files (x86)/Java/jre7/bin/java.exe"
filters:
    yui_css:
        #2.4.8 fail on windows
        jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

**Comment by mzagai** [comment]
@Hofferic Thank you for the file! Works llike a charme in my Symfony app

**Comment by dec** [comment]
I also experiment this same issue here in Windows 10 Pro, thanks for your consideration @Hofferic, your JAR works like a charm!
