### ISSUE TITLE
error :missing name after . operator

### ISSUE THREAD

**Issue by mustapha-wang** [yui/yuicompressor#171]
https://www.npmjs.org/package/node-rsa
https://www.npmjs.org/package/browserify
I hava a file rsa.js，generated by browserify -r node-rsa/NodeRSA.js >rsa.js
When I want to minimize it,I got a error:"716:14:missing name after . operator"
the 176 line source code is:
assert.throws = function(block, /_optional_/error, /_optional_/message) {

**Comment by skellman** [comment]
I have hundreds of errors where the location says unknown-file:xxxx:xx (see example below)
[ERR] C2009: YUI Parse Error (invalid return =>             return target;) -- unknown-file:5520:19

How can I tell what file the error is in?
