### ISSUE TITLE
CssCompressor.java have issues , the 0% shouldn't compress to 0

### ISSUE THREAD

**Issue by perfect** [yui/yuicompressor#184]
0% {
		-moz-transform-origin: bottom center;
		-moz-transform: perspective(999px) rotateX(90deg);
		top: -100%;
	}

compreess to 
0   {   	-moz-transform-origin: bottom center;
		-moz-transform: perspective(999px) rotateX(90deg);
		top: -100%;
	}

It's not right. 0%  -->0

**Comment by denizdogan** [comment]
Looks like a duplicate of #151

**Comment by perfect** [comment]
thank U.  It's a same bug

**Comment by tml** [comment]
@perfect maybe you can comment on #151 whether the bug is fixed for you in HEAD?

**Comment by perfect** [comment]
@tml    Done

**Comment by tml** [comment]
Closed per #151

**Comment by bluemoehre** [comment]
Thought this was solved?! Current HEAD fails with this.

**Comment by jochenberger** [comment]
Should be fixed in master (see #231)
