### ISSUE TITLE
yui-compressor fails to evaluate reserved words in expressions

### ISSUE THREAD

**Issue by ajkret** [yui/yuicompressor#186]
When entering expressions like this one:

    var span=document.createElement('span');
    span.style.float="right";

It generates the following error:

    missing name after . operator

I belive the 'float' element is the problem. As a workaround, I use this:

     eval('span.style.float="right"');

**Comment by tml** [comment]
Yes, this is issue #47 all over again - in brief, this is not allowed in ES3 (which is what Rhino supports, and Rhino is what provides the JS engine for YUICompressor).

**Comment by elFua** [comment]
@ajkret: no need for eval, replacing dot notation with string-based property accessors works fine:

```js
var span=document.createElement('span');
span.style["float"]="right";
```
