### ISSUE TITLE
Why does yuicompressor not work with Java 8?

### ISSUE THREAD

**Issue by eszekeres** [yui/yuicompressor#191]
On a Windows 7 system, we have been requested to update our Java. However, now yuicompressor won't run, and give this message:

Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.

Why would it be hardcoded to 1.7?  Does a check need to be updated.

**Comment by tml** [comment]
I'm not aware of anything in YUICompressor that should be reading from the Windows Registry; perhaps one of our Windows users might have some insight? @Hofferic, @mwikblom, @iignatov - you have all chimed in on Windows related issues in the past, do any of you have thoughts on this?

**Comment by tml** [comment]
@eszekeres Perhaps [this](http://stackoverflow.com/questions/15277496/registry-key-has-value-1-7-but-1-6-is-required-java-1-7-is-installed) StackOverflow link points at something that might be useful?

**Comment by eszekeres** [comment]
thanks,

with a bit of digging it was

**Comment by eszekeres** [comment]
To clarify for others because my initial response really was not helpful.

The issue was “left over” java executables on the system.  The StackOverflow  discussion pointed in that direction.  Turns out that I had to search the Windows system directories and other locations and remove all executables that were in legacy locations, once they were removed the error was resolved.
