### ISSUE TITLE
Method not found: 'System.String Yahoo.Yui.Compressor.ICompressor.get_ContentType()'

### ISSUE THREAD

**Issue by GlenBoonzaier** [yui/yuicompressor#202]
This is the first time I have used the YUI Compressor.  I get this error in my layout on this line:
    @Styles.Render("~/Content/css")

My bundle config looks like this:

    // Use YUI Compressor to minify javascript
    var javascriptConfig = new JavaScriptCompressorConfig();
    var javascriptTransform = new YuiCompressorTransform(javascriptConfig);

    bundles.Add(new Bundle("~/bundles/jquery", javascriptTransform).Include("~/Scripts/jquery-{version}.js"));
    bundles.Add(new Bundle("~/bundles/modernizr", javascriptTransform).Include("~/Scripts/modernizr-*"));
    bundles.Add(new Bundle("~/bundles/bootstrap", javascriptTransform).Include("~/Scripts/bootstrap.js", "~/Scripts/respond.js"));

    // Use YUI Compressor to minify css
    var cssConfig = new CssCompressorConfig();
    var cssTransform = new YuiCompressorTransform(cssConfig);

    bundles.Add(new Bundle("~/Content/css", cssTransform).Include("~/Content/bootstrap.css", "~/Content/widget.css"));

My packages shows YuiCompressor.Net is installed correctly

    <package id="YUICompressor.NET" version="2.0.0.0" targetFramework="net451" />
    <package id="YUICompressor.NET.Web.Optimization" version="2.7.0.0" targetFramework="net451" />

I followed the tutorial on YouTube:  https://www.youtube.com/watch?v=NSHGSbViMm8

The full error is this:

    Stack Trace: 

    [MissingMethodException: Method not found: 'System.String Yahoo.Yui.Compressor.ICompressor.get_ContentType()'.]
    Yahoo.Yui.Compressor.Web.Optimization.YuiCompressorTransform.Process(BundleContext context, BundleResponse response) +0
    System.Web.Optimization.Bundle.ApplyTransforms(BundleContext context, String bundleContent, IEnumerable`1 bundleFiles) +263
    System.Web.Optimization.Bundle.GenerateBundleResponse(BundleContext context) +355
    System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context) +104
    System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath) +254
    System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable`1 assets) +252
    System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths) +75
    System.Web.Optimization.Styles.RenderFormat(String tagFormat, String[] paths) +293
    System.Web.Optimization.Styles.Render(String[] paths) +51
    ASP._Page_Views_Shared__Layout_cshtml.Execute() in c:\TFS_Workspace\NewProj\Main\Source\NewProj.Presentation.Widget\Views\Shared\_Layout.cshtml:7
    System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +271
    System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +121
    System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +145
    System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer) +41
    System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +335
    System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +42
    System.Web.WebPages.WebPageExecutingBase.WriteTo(TextWriter writer, HelperResult content) +45
    System.Web.WebPages.WebPageBase.Write(HelperResult result) +53
    System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +178
    System.Web.WebPages.WebPageBase.PopContext() +229
    System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +154
    System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +695
    System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +382
    System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +431
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +39
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +116
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +529
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +106
    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +321
    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +42
    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +133
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +56
    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +40
    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +34
    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +139
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +59
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +40
    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +44
    System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +39
    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +62
    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +139
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +59
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +40
    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +39
    System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +39
    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +39
    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +139
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +59
    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +40
    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +40
    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +38
    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +932
    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +188
    
    Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34248

**Comment by tml** [comment]
This YouTube video appears to be referring to the project "YUICompressor.net" (https://github.com/PureKrome/YUICompressor.NET), which - regardless of the naming similarity - isn't related to this project (YUICompressor.)
