### ISSUE TITLE
compressor fails on Promise.prototype.catch

### ISSUE THREAD

**Issue by WesleydeSouza** [yui/yuicompressor#203]
When using the [`.catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) method from promises, the compressor fails.

Here's the input source that should compile properly:

```js
var promise = new Promise(function (resolve, reject) {
    reject(new Error('Test'));
} );
promise
    .then(function(){console.log('success')})
    .catch(function(e) {console.error(e)});
```

Output:
```sh
[ERROR] in promise-test.js
  6:8:missing name after . operator
[ERROR] in promise-test.js
  1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

The expected behavior for me would be to change it to ['catch'] so it is compatible with IE ≤ 8.

Using 2.4.8.

**Comment by trullock** [comment]
+1, just encountered this

**Comment by sgryschuk-va** [comment]
+1, same here

**Comment by scottchantry** [comment]
+1, same issue here

**Comment by hmillet** [comment]
+1, same with 
```
promise
    .then(function(){console.log('success')})
    .finally(function() { ... });
```

**Comment by hmillet** [comment]
I've switched to https://github.com/mishoo/UglifyJS2

As The YUI Compressor is no longer maintained by Yahoo

**Comment by thiagoh** [comment]
+1, just encountered this

**Comment by PranceTheDeer** [comment]
Another option that worked for me was to use a `.then(successFunction, failureFunction)` approach for simple promise resolution.  The yui-compressor didn't complain.  

```
promise.then(successFunction, failureFunction);

function successFunction() {
   console.log('success');
}

function failureFunction(err) {
    console.error(err);
}
```

**Comment by alonando** [comment]
A possible workaround is using an alias for the 'catch' function. 

`Promise.prototype.error = Promise.prototype['catch'];`

Then instead of `.catch(...)` use `.error(...)`

**Comment by tml** [comment]
It's a bit unfair to call these "bugs" in YUICompressor; YUICompressor explicitly only supports ECMAScript version 3, and the constructs giving you problems are not valid in ECMAScript 3. That said, if someone wants to take a crack at replacing the decompiler with the newer Rhino implementation based on AST, that'd go a long way to making it easier to fix these problems. :)

**Comment by trullock** [comment]
isnt this issue fixed?

**Comment by 1Hyena** [comment]
I personally have no problem with the fact that it supports only the old version, but there's a bug with CSS calc function that really bothers me.

Here's the bug and a workaround. Maybe it's been fixed IDK, but if not then beware of the below:

```CSS
height: calc(40vmin - -1px);  /* substracting a negative number is a workaround for a yui-compressor bug that makes the spaces disappear around + sign */
```
