### ISSUE TITLE
Compress signature changed

### ISSUE THREAD

**Issue by joekukish** [yui/yuicompressor#211]
The compress signature changed from
```
 public void compress(Writer out, int linebreak, boolean munge, boolean verbose,
            boolean preserveAllSemiColons, boolean disableOptimizations)
```
to
```
 public void compress(Writer out, Writer mungemap, int linebreak, boolean munge, boolean verbose,
            boolean preserveAllSemiColons, boolean disableOptimizations)
```

This is a breaking change that will cause problems with current implementations.

It was changed in the following commit: https://github.com/yui/yuicompressor/commit/d3a60d9261bbf87b2e437ed53bbdc2f574141906

**Comment by tml** [comment]
@joekukish Thanks for reaching out. I'm hoping fixing this would progress getting the new release in AEM?

**Comment by joekukish** [comment]
@tml yeah it would.

**Comment by tml** [comment]
@joekukish I realize you probably can't give a lot of specifics, but would fixing this allow 2.4.9 to be included in a 6.1 service pack, or is that something that'd have to wait for the next major release? If the former, I can probably make the argument to my day job to spend some on-the-clock time finishing up a 2.4.9, as this is a priority for my employer.

**Comment by joekukish** [comment]
@tml I can certainly make a case for it given the importance of the update. This is something that would benefit a lot of people, so it seems viable for me. Thank you for your help!

**Comment by joekukish** [comment]
@tml hey, do you have any updates? :)

**Comment by joekukish** [comment]
@tml Thanks! are you planning a release?
