### ISSUE TITLE
MSBuild task should not use lib

### ISSUE THREAD

**Issue by SimonCropp** [yui/yuicompressor#212]
since this results in a copy local reference and the dlls get deployed. 

if we are compressing at build time we dont need this??

If the above is correct the dlls used by msbuild should instead exist in the root of the package

it would also simplify the implementation if u shipped a msbuild file inside the build dir of the nuget that just imported the tasks and then was auto included in the target .csproj

Do you want a PR illustrating the above?

**Comment by tml** [comment]
Hi, Simon - it appears, from the question, that you may be looking for the YUICompressor.NET project, which can be found at https://github.com/PureKrome/YUICompressor.NET
