### ISSUE TITLE
The any char after '\0' is remove.

### ISSUE THREAD

**Issue by mwkang** [yui/yuicompressor#222]
When I use `com.yahoo.platform.yui.compressor.CssCompressor`,
try compressing `@media \0screen`.
I expect `@media \0screen`. But the result is `@media \0creen`.
's' is remove. So css is broken. It is not work.

yuicompressor version is 2.4.8

**Comment by jochenberger** [comment]
Should be fixed in master (see #231)

**Comment by mwkang** [comment]
Thanks.
Closed by #231
