### ISSUE TITLE
YUI Compressor is breaking some CSS, specifically calc(100% + ##px)

### ISSUE THREAD

**Issue by djgilcrease** [yui/yuicompressor#59]
```
.issue-59 {
    width:100%;
    width: -webkit-calc(100% + 30px);
    width: -moz-calc(100% + 30px);
    width: calc(100% + 30px);
}
```

turns into
`.issue-59{width:100%;width:-webkit-calc(100%+30px);width:-moz-calc(100%+30px);width:calc(100%+30px)}`

instead of

`.issue-59{width:100%;width:-webkit-calc(100% + 30px);width:-moz-calc(100% + 30px);width:calc(100% + 30px)}`

Notice the missing spaces

**Comment by jamespero** [comment]
Found a word around for the plus sign issue... 

calc(X% - -Xpx)

Subtracting a negative number retains the white space.

**Comment by timbru31** [comment]
@jamespero Thanks for the hint.
This saved some headache in our team, since a v2.4.9 won't be released soon :(

**Comment by victole** [comment]
hi all, does this has already been solved?

**Comment by MorrisJohns** [comment]
Since this will never be fixed, I use a Python function to fix up the file by reinserting spaces around +:

def fixYuiCompressorBug(oldCss):
	calcRx = re.compile('calc[(]([^ )\r\n;]+[+][^ ])+', re.MULTILINE)
	plusRx = re.compile('[+]', re.MULTILINE)
	def fixCss(match):
		return 'calc(' + plusRx.sub(' + ', match.group(1))
	return calcRx.sub(fixCss, oldCss)

**Comment by isafin** [comment]
How this may be closed?! This problem still alive :\

And that solving calc(X% - -Xpx) — shit CSS code.

**Comment by msunasra** [comment]
This is an issue of the optimizer.

To avoid the miniffier to remove the whitespaces, group the affected element with parenthesis. That workarrounds the issue.

margin-left: calc((50%) - 480px);

Source: [StackOverFlow](http://stackoverflow.com/questions/20888030/mvc-bundling-breaking-my-calc-css-statements-by-removing-spaces)

**Comment by nineoclick** [comment]
**Encountered this bug and found a solution that works great for me.**
My setup is: PhpStorm with LESS and YUI Compressor CSS watchers. So usually I work with a less file, that outputs to css file and then YUI Compressor as watcher minifies the css.

**My solution**

Less File:
```
.@{css_root}-mainContentRight {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  display: inline-block;
  height: 200px;
  width: calc(~"100% -  " @mainContentDivDefaultMargin*4 + @mainContentLeftWidth);
  background: #bacd63;
  padding: @mainContentDivDefaultPadding;
  margin: @mainContentDivDefaultMargin;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}
```
Now: on width rule, I put **two** spaces between the **minus** sign AND **one** space after closing the unescaped string. **See below**:
`width: calc(~"100% -`**SpaceSpace**`"`**Space**`@mainContentDivDefaultMargin*4 + @mainContentLeftWidth);`

CSS not compressed that results from LESS

```
.jimlibmus-mainContentRight {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  display: inline-block;
  height: 200px;
  width: calc(100% -   220px);
  background: #bacd63;
  padding: 5px;
  margin: 5px;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}
```

`width: calc(100% -`**SpaceSpaceSpace**`220px);`

Phpstorm watcher see changes in css file and then starts YUI. The result:

`.jimlibmus-mainContentRight{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline-block;height:200px;width:calc(100% - 220px);background:#bacd63;padding:5px;margin:5px;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px}`

Now YUI compresses it right.

`width:calc(100% -`**Space**`220px);`

It's simple to become familiar with this ***multiple-space*** practice, and helps me a lot not to banging my head on the desk.

Hope this helps.

**Comment by himanshuwt** [comment]
Still Facing Issue.
**Please tell me work around for this**

.target {
    width: calc(100% + 20px);
}
turns into
.target{width:calc(100%+20px)}

instead of

.target {width: calc(100% + 20px);}

**Comment by manishmp7** [comment]
facing same issue
I'm using "2.4.8" version.

Team, Please fix it or tell me how can i fix it without (- -) solution

**Comment by svaponi** [comment]
Compression examples:
```
calc(50% - 3px)      => calc(50% - 3px)   // VALID
calc(50% + 3px)      => calc(50%+3px)     // INVALID
calc(50% + +3px)     => calc(50%++3px)    // INVALID
calc((50%) + (3px))  => calc((50%)+(3px)) // INVALID
calc(50% + (+3px))   => calc(50%+(+3px))  // INVALID
calc(50% + (3px))    => calc(50%+(3px))   // INVALID
calc(50% - (-3px))   => calc(50% -(-3px)) // INVALID
calc(50% - -3px)     => calc(50% - -3px)  // VALID

```

**Comment by PeterLenahan** [comment]
Before compression spaces are there
	.file-item {
		width: calc(100vw - 40px);
		height: calc(((100vw - 40px) * .73) + 40px);
	}
After compression, the spaces are missing.

.file-item{width:calc(100vw - 40px);height:calc(((100vw - 40px) * .73)+40px)}

**Comment by sunnybear** [comment]
Any news on this? YUI Compressor breaks CSS calc for 5 years!

**Comment by himanshuwt** [comment]
@sunnybear agree with you. 5 years done. And, still I faced the issue "+" then again i replace it with calc(x - - y). :D

**Comment by sunnybear** [comment]
Does anybody have a list of issues with calc? We've faced with
100% + 6px -> 100%+px
100% - (10% * 6) -> 100% -(10% * 6)
It seems also
(100vw - 40px) * .73) + 40px -> (100vw - 40px) * .73)+ 40px

**Comment by MarjanAshofteh** [comment]
@beaktor 
using two - beside + work for me too.
thanks

**Comment by ramarro123** [comment]
it's yui compressor still mantained?

**Comment by DrLightman** [comment]
Using YuiCompressor 2.4.8 and the bug is still on.

**Comment by frangarcia** [comment]
This version, https://mvnrepository.com/artifact/com.yahoo.platform.yui/yuicompressor/2.4.9-BSI-2, seems to have fixed the problem. I followed the examples @svaponi added using this file

```
body{
	font-size: calc(50% - 3px);
	font-size: calc(50% + 3px);
	font-size: calc(50% + +3px);
	font-size: calc((50%) + (3px));
	font-size: calc(50% + (+3px));
	font-size: calc(50% + (3px));
	font-size: calc(50% - (-3px));
	font-size: calc(50% - -3px);
}
```

and when running this command:

```java -jar yuicompressor-2.4.9-BSI-2.jar --line-break 0 -o process.css.min file.css```

this output was generated:

```body{font-size:calc(50% - 3px);font-size:calc(50% + 3px);font-size:calc(50% + +3px);font-size:calc((50%)+(3px));font-size:calc(50% + (+3px));font-size:calc(50% + (3px));font-size:calc(50% - (-3px));font-size:calc(50% - -3px)}```

which looks correct.

It seems the repo in charge of this is this fork https://github.com/BSI-Business-Systems-Integration-AG/yuicompressor

**Comment by Aleuck** [comment]
This is not correct, @frangarcia 
`calc((50%)+(3px))`

**Comment by R-W-C** [comment]
September 2022 and still broken.
Version 2.4.8 has got several bugs. One of them is described here: https://stackoverflow.com/a/19339287/760777
Version 2.4.9 has never been released.

So back to version 2.4.7
There is the calc bug. Just use the double minus solution.

So 

left: calc(100%	+ 14px);

becomes

left: calc(100 -  -14px);  /* + replaced with - - because of yuicompressor bug */
