### ISSUE TITLE
Doesn't like "class" in javascript objects

### ISSUE THREAD

**Issue by pdavis68** [yui/yuicompressor#77]
I have the following piece of code that YUICompressor doesn't like:

```
var listitem = $("<li>").
    append($("<a>", 
    { 
        href: "#", 
        class: "searchanchor", 
        id: result.Id, onclick: "search_navigate('" + result.Url + "');", 
        text: result.Title })).
    append($("<p>", { class: "searchdescription", text: result.Description }));
```

The compressor doesn't like the "class:" stuff. But this code functions properly for me, so I'm guessing YUICompressor is at fault. I'm not a javascript pro, so I could be wrong.

**Comment by pieroxy** [comment]
So... Plenty of years later this is still not fixed. It is failing for outside libs that I'm using now. Any updates ?
