### ISSUE TITLE
empty javascript with \n produces an exception

### ISSUE THREAD

**Issue by alejandroanadon** [yui/yuicompressor#92]
If we try to compress a javascript with only a "\n" character, it produces an Exception.
I founded the issue source.
In JavaScriptCompressor.java , in
private StringBuffer printSymbolTree(int linebreakpos, boolean preserveAllSemiColons) function, it has a:

 JavaScriptToken lastToken = getToken(0); 

But it does not care if "tokens.size()==0".. so when it tries to retrieve the token, it produces the Exception.

I changed in my version to:

JavaScriptToken lastToken = null;
int length = tokens.size();
if(tokens.size()>0)
    lastToken = getToken(0);

I proved and it seems to work.

**Comment by tml** [comment]
Closing in favor of #130
