### ISSUE TITLE
YUI Compressor is not ES5 complaint.

### ISSUE THREAD

**Issue by scrapmac** [yui/yuicompressor#98]
If your code is like
```javascript
var foo = {
  delete : "asd"
};
```
then the compressor will give syntax errors, while the code is perfectly correct as per ES5, but is incorrect as per ES3.

Are there any plans to support ES5, or if you already are supporting ES5, then consider this as a new bug.

**Comment by tml** [comment]
Tracking all versions of this issue on #47, closing the rest so that I only have one bug to keep track of for all the variants of the problem.
